language: android
jdk:
  - oraclejdk8

android:
  components:

    - build-tools-23.0.0
    - android-23

licenses:
	- 'android-sdk-preview-license-.+'
	- 'android-sdk-license-.+'
	- 'google-gdk-license-.+'
notifications:
  email: true

cache: false

sudo: false

install:

  - chmod +x ./gradlew; ls -l gradlew; ./gradlew wrapper -v

script:
  - ./gradlew clean assembleDebug

