language: android
jdk:
  - oraclejdk8

android:
  components:
	- tools
	- platform-tools
    - build-tools-25.0.0
    - android-25
	- extra-android-m2repository

notifications:
  email: true

cache: false

sudo: false

install:

  - chmod +x ./gradlew; ls -l gradlew; ./gradlew wrapper -v

script:
  - ./gradlew clean assembleDebug
